INSERT INTO books (name) VALUES 
('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА'),
('Программирование на языке Go!'),
('Толковый словарь сетевых терминов и аббревиатур'),
('Python for Data Analysis'),
('Thinking in Java (4th Edition)'),
('Introduction to Algorithms'),
('JavaScript Pocket Reference'),
('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles'),
('SQL: The Complete Referenc'),
('PHP and MySQL Web Development'),
('Статистический анализ и визуализация данных с помощью R'),
('Computer Coding for Kid'),
('Exploring Arduino: Tools and Techniques for Engineering Wizardry'),
('Программирование микроконтроллеров для начинающих и не только'),
('The Internet of Things'),
('Sketching User Experiences: The Workbook'),
('InDesign CS6'),
('Адаптивный дизайн. Делаем сайты для любых устройств'),
('Android для разработчиков'),
('Clean Code: A Handbook of Agile Software Craftsmanship'),
('Swift Pocket Reference: Programming for iOS and OS X'),
('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence'),
('Head First Ruby'),
('Practical Vim');

INSERT INTO authors (name) VALUES 
('Андрей Богуславский'),
('Марк Саммерфильд'),
('М., Вильямс'),
('Уэс Маккинни'),
('Брюс Эккель'),
('Томас Кормен'),
('Чарльз Лейзерсон'),
('Рональд Ривест'),
('Клиффорд Штайн'),
('Дэвид Флэнаган'),
('Гэри Маклин Холл'),
('Джеймс Р. Грофф'),
('Люк Веллинг'),
('Сергей Мастицкий'),
('Джон Вудкок'),
('Джереми Блум'),
('А. Белов'),
('Сэмюэл Грингард'),
('Сет Гринберг'),
('Александр Сераков'),
('Тим Кедлек'),
('Пол Дейтел'),
('Харви Дейтел'),
('Роберт Мартин'),
('Энтони Грей'),
('Мартин Фаулер'),
('Прамодкумар Дж. Садаладж'),
('Джей Макгаврен'),
('Дрю Нейл');

INSERT INTO books_authors (book, author) VALUES 
('1','1'),
('2','2'),
('3','3'),
('4','4'),
('5','5'),
('6','6'),
('6','7'),
('6','8'),
('6','9'),
('7','10'),
('8','11'),
('9','12'),
('10','13'),
('11','14'),
('12','15'),
('13','16'),
('14','17'),
('15','18'),
('16','19'),
('17','20'),
('18','21'),
('19','22'),
('19','23'),
('20','24'),
('21','25'),
('22','26'),
('22','27'),
('23','28'),
('24','29');